# Этап сборки
FROM golang:1.20 AS builder

# Установите рабочую директорию
WORKDIR /app

# Скопируйте go.mod и go.sum файлы
COPY go.mod go.sum ./
RUN go mod download

# Скопируйте исходный код
COPY . .

# Соберите исполняемый файл
RUN go build -o my-terminal .

# Этап финального образа
FROM alpine:latest

# Скопируйте исполняемый файл из этапа сборки
COPY --from=builder /app/my-terminal /usr/local/bin/my-terminal

# Установите точку входа
ENTRYPOINT ["my-terminal"]
